server.port=0
spring.application.name=auth-service
eureka.instance.preferIpAddress=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka
spring.cloud.compatibility-verifier.enabled=false
spring.cloud.config.uri=http://localhost:8071
spring.config.import=configserver:
logging.level.org.springframework.web=warn
logging.level.com.example=debug

security.key=MAUPOVKA_TEST

spring.kafka.consumer.group-id=auth
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=com.example.authservice.kafka.UserDtoDeserializer