spring.application.name=game-service
server.port=0
eureka.instance.preferIpAddress=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka

spring.cloud.compatibility-verifier.enabled=false

logging.level.org.springframework.web=warn
logging.level.com.example=debug

spring.kafka.producer.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=com.example.gameservice.events.kafka.GameSerializer

security.key=MAUPOVKA_TEST