spring.application.name=api-gateway
spring.cloud.config.uri=http://config-server:8071
spring.config.import=configserver:
server.port=8072

spring.cloud.compatibility-verifier.enabled=false
logging.level.org.springframework.web=warn
logging.level.com.example=debug
