spring.application.name=user-service
spring.cloud.config.uri=http://localhost:8071
spring.config.import=configserver:
spring.cloud.config.profile=dev

server.port=0
eureka.instance.preferIpAddress=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka

spring.cloud.compatibility-verifier.enabled=false
logging.level.org.springframework.web=warn
logging.level.com.example=debug

spring.kafka.consumer.group-id=user
spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=com.example.userservice.kafka.GameDeserializer