eureka.instance.preferIpAddress=true
eureka.client.serviceUrl.defaultZone=http://localhost:8070/eureka
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lowerCaseServiceId=true

spring.cloud.gateway.routes[0].id=game-service
spring.cloud.gateway.routes[0].uri=lb://game-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/v1/game/**

spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=lb://user-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/v1/user-service/**

spring.cloud.gateway.routes[2].id=wallet-service
spring.cloud.gateway.routes[2].uri=lb://wallet-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/v1/wallet/**

